Fix version extraction from package.json

diff --git a/.ci/buildspec_ci.yml b/.ci/buildspec_ci.yml
--- a/.ci/buildspec_ci.yml
+++ b/.ci/buildspec_ci.yml
@@ -6,15 +6,12 @@ phases:
 
   build:
     commands:
-      - VERSION=$(jq .version package.json)
+      - VERSION=$(jq -r .version package.json)
       - ALL_VERSIONS=$(aws codeartifact list-package-versions --package milkman-api-js-client --namespace milkman --domain milkmantechnologies --repository milkman --format npm --query 'versions[*].[version]' --output text)
       - PRESENT=$(echo "$ALL_VERSIONS" | sed -n "/$VERSION/p") 
 
-      - |
-        if [ -n "$ALREADY_DEPLOYED" ]; then
-          echo "ERROR: Version $VERSION already deployed on CodeArtifact! Please update the version of your package"
-          exit 1
-        fi
+      - |-
+        [ -n "$ALREADY_DEPLOYED" ] && echo "ERROR: Version $VERSION already deployed on CodeArtifact! Please update the version of your package"; exit 1
 
       - npm install
       - npm test 
